import { Prisma } from "@nyumba/db";

export const PROPERTY_CARD_SELECT = {
  id: true,
  slug: true,
  title: true,
  category: true,
  type: true,
  listingType: true,
  status: true,
  price: true,
  currencyCode: true,
  priceNote: true,
  district: true,
  lat: true,
  lng: true,
  bedrooms: true,
  bathrooms: true,
  sizeSqm: true,
  verificationStatus: true,
  isFeatured: true,
  viewCount: true,
  likeCount: true,
  createdAt: true,
  publishedAt: true,
  // Flat scalars alongside the nested relation objects below — canManageProperty()
  // and other authorization checks compare against these directly.
  ownerId: true,
  companyId: true,
  city: { select: { id: true, name: true } },
  country: { select: { code: true, name: true, flagEmoji: true, currencySymbol: true } },
  owner: { select: { id: true, name: true, avatarUrl: true, role: true, verificationStatus: true } },
  company: { select: { id: true, name: true, slug: true, logoUrl: true } },
  media: {
    select: { id: true, type: true, url: true, thumbnailUrl: true, isPrimary: true, order: true },
    orderBy: [{ isPrimary: "desc" }, { order: "asc" }] as const,
    take: 6,
  },
  liveStreams: {
    where: { status: "LIVE" as const },
    select: { id: true, currentViewers: true },
    take: 1,
  },
  _count: { select: { favorites: true } },
} satisfies Prisma.PropertySelect;

export const PROPERTY_DETAIL_SELECT = {
  ...PROPERTY_CARD_SELECT,
  description: true,
  address: true,
  parkingSpaces: true,
  landSizeSqm: true,
  yearBuilt: true,
  furnished: true,
  amenities: true,
  countryId: true,
  cityId: true,
  media: {
    select: {
      id: true,
      type: true,
      url: true,
      thumbnailUrl: true,
      isPrimary: true,
      order: true,
      caption: true,
      meta: true,
    },
    orderBy: [{ isPrimary: "desc" }, { order: "asc" }] as const,
  },
  owner: {
    select: {
      id: true,
      name: true,
      avatarUrl: true,
      role: true,
      bio: true,
      whatsapp: true,
      phone: true,
      verificationStatus: true,
      createdAt: true,
      _count: { select: { properties: true, agentFollowers: true } },
    },
  },
  company: {
    select: { id: true, name: true, slug: true, logoUrl: true, verificationStatus: true },
  },
  reviews: {
    orderBy: { createdAt: "desc" as const },
    take: 20,
    select: {
      id: true,
      rating: true,
      comment: true,
      createdAt: true,
      author: { select: { id: true, name: true, avatarUrl: true } },
    },
  },
} satisfies Prisma.PropertySelect;
